Repository wecode-bootcamp-korea/50-2nd-Dobby-frontend, pull requests merged in 2023-11, with the labels that each got.

#25 비밀번호 찾기 페이지 제작
  src/Router.jsx
  src/components/Footer/Footer.jsx
  src/pages/FindPW/FindPW.jsx
  src/pages/FindPW/FindPW.scss
Labels: 멘토 리뷰 요청, 수정 요청

#22 메인페이지 제품 슬라이드 UI, 기능 구현
  .vscode/settings.json
  package-lock.json
  package.json
  public/data/menu.json
  public/data/slideList.json
  public/images/icon_basic.svg
  public/images/icon_collection.svg
  public/images/icon_creative.svg
  public/images/icon_star.svg
  public/images/sampleIcon.png
  sampleIcon.png
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.scss
  src/components/Carousel/NextBtn.jsx
  src/components/Carousel/NextBtn.scss
  src/components/Carousel/PrevBtn.jsx
  src/components/Carousel/PrevBtn.scss
  src/components/Category/Category.jsx
  src/components/Category/Category.scss
  src/components/ProductCard/ProductCard.jsx
  src/components/ProductCard/ProductCard.scss
  src/config.js
  src/pages/Main/Layout/CategorizedSlide/CategorizedSlide.jsx
  src/pages/Main/Layout/CategorizedSlide/CategorizedSlide.scss
  src/pages/Main/Layout/CategoryList/CategoryList.jsx
  src/pages/Main/Layout/CategoryList/CategoryList.scss
  src/pages/Main/Layout/CategoryTitle/CategoryTitle.jsx
  src/pages/Main/Layout/CategoryTitle/CategoryTitle.scss
  src/pages/Main/Layout/SUBSCRIPTION.js
  src/pages/Main/Layout/Subscribe.jsx
  src/pages/Main/Layout/Subscribe.scss
  src/pages/Main/Layout/Subscribe/Subscribe.jsx
  src/pages/Main/Layout/Subscribe/Subscribe.scss
  src/pages/Main/Layout/TabContent/TabContent.jsx
  src/pages/Main/Layout/TabContent/TabContent.scss
  src/pages/Main/Layout/TabList/TabList.jsx
  src/pages/Main/Layout/TabList/TabList.scss
  src/pages/Main/Layout/TitleText/TitleText.scss
  src/pages/Main/Layout/subscription.js
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#29 Nav바 Cart-Icon 수정
  src/components/Nav/Cart-icon.png
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.scss
  src/components/Nav/cartIcon.png
Labels: 멘토 리뷰 요청

#2 로그인 페이지 추가
  .bash_profile
  package-lock.json
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#30 Modify : 리뷰 반영
  public/data/data.json
  src/pages/Payment/Payment.jsx
Labels: 멘토 리뷰 요청

#24 아이디 찾기 페이지 제작
  src/Router.jsx
  src/pages/FindID/FindID.jsx
  src/pages/FindID/FindID.scss
Labels: 멘토 리뷰 요청

#20 장바구니 페이지
  src/Router.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/Layout/Layout.scss
  src/components/Nav/Nav.scss
  src/config.js
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.scss
  src/styles/reset.scss
Labels: Conflict 해결 요청

#26 비밀번호 찾기 페이지 기능구현
  package-lock.json
  src/Router.jsx
  src/components/Footer/Footer.jsx
  src/pages/FindID/FindID.jsx
  src/pages/FindID/FindID.scss
  src/pages/FindPW/FindPW.jsx
  src/pages/FindPW/FindPW.scss
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#11 로그인 페이지 기능구현
  src/Router.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
  src/pages/Signup/Signup.jsx
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#31 스토어 페이지 (UI,기능) 추가
  public/data/menu.json
  public/data/slideList.json
  src/Router.jsx
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.scss
  src/components/Carousel/NextBtn.scss
  src/components/Carousel/PrevBtn.scss
  src/components/Category/Category.scss
  src/components/Nav/Nav.jsx
  src/components/ProductCard/ProductCard.jsx
  src/config.js
  src/pages/Main/Main.jsx
  src/pages/Store/Layout/ProductList.jsx
  src/pages/Store/Layout/ProductList.scss
  src/pages/Store/Layout/Sorting.jsx
  src/pages/Store/Layout/Sorting.scss
  src/pages/Store/Store.jsx
  src/pages/Store/Store.scss
Labels: 멘토 리뷰 요청

#23 결제 페이지 daum api 주소 검색 팝업 구현중
  package-lock.json
  package.json
  public/data/Mockdata.json
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.scss
  src/pages/Payment/components/Address.jsx
  src/pages/Payment/components/Address.scss
Labels: Conflict 해결 요청, 수정 요청

#19 회원가입 페이지 기능구현
  src/Router.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#28 아이디 찾기 페이지 기능구현
  src/Router.jsx
  src/components/Footer/Footer.jsx
  src/pages/Login/Login.jsx
Labels: Conflict 해결 요청, 수정 요청

#32 아이디 찾기 기능구현 - router 수정 완료
  src/Router.jsx
Labels: 멘토 리뷰 요청

#34 장바구니 구매하기 버튼 서버 확인
  src/components/Layout/Layout.scss
  src/config.js
  src/pages/Cart/Cart.jsx
Labels: 멘토 리뷰 요청

#35 백엔드 배송지 통신 작업 완료
  src/pages/Payment/Payment.jsx
Labels: 멘토 리뷰 요청

#37 Add. FindID-Func : fetch 함수 추가
  public/data/MockData.json
  src/pages/FindID/FindID.jsx
Labels: 멘토 리뷰 요청

#44 제품 상세페이지 config 설정
  src/config.js
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Detail.scss
Labels: 멘토 리뷰 요청

#51 Add. FindID-Func 브랜치에 FindPW-Func 기능 추가 완료
  src/pages/FindPW/FindPW.jsx
  src/pages/FindPW/FindPW.scss
Labels: 멘토 리뷰 요청

#52 Add. 로그인 & 회원가입 페이지 기능 일부 수정 완료
  src/pages/Login/Login.jsx
  src/pages/Signup/Signup.jsx
Labels: 멘토 리뷰 요청

#49 Add. FindPW-Func 기능 수정(완료)
  src/pages/FindID/FindID.jsx
  src/pages/FindPW/FindPW.jsx
Labels: 멘토 리뷰 요청

#53 store페이지 필터링 기능 수정
  src/Router.jsx
  src/components/Category/Category.jsx
  src/config.js
  src/pages/Main/Layout/subscription.js
  src/pages/Main/Main.jsx
  src/pages/Store/Layout/ProductList.jsx
  src/pages/Store/Layout/Sorting.jsx
  src/pages/Store/Layout/Sorting.scss
  src/pages/Store/Store.jsx
Labels: 멘토 리뷰 요청
