Repository wecode-bootcamp-korea/50-2nd-Dobby-frontend, pull requests merged in 2023-10, with the labels that each got.

#1 공통 레이아웃 추가
  src/Router.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/Layout/Layout.jsx
  src/components/Layout/Layout.scss
  src/pages/Login/Login.jsx
Labels: 멘토 리뷰 요청, 수정 요청

#4 배송지 목록 페이지 추가
  src/Router.js
  src/pages/Delivery/Delivery.jsx
  src/pages/Delivery/Delivery.scss
Labels: 멘토 리뷰 요청

#3 1. 장바구니 페이지 추가
  public/images/cart_sample.jpg
  public/images/icon_check.png
  public/images/icon_close.png
  public/images/icon_minus.png
  public/images/icon_plus.png
  src/Router.js
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.scss
Labels: Conflict 해결 요청, 수정 요청

#12 결제 페이지 추가
  src/Router.js
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.scss
Labels: 멘토 리뷰 요청

#13 배송지 목록 -> 배송지 추가로 변경
  src/pages/Delivery/Delivery.jsx
  src/pages/Delivery/Delivery.scss
Labels: 멘토 리뷰 요청

#17 공통 버튼 리셋 추가
  src/pages/Cart/Cart.scss
  src/pages/Delivery/Delivery.scss
  src/pages/Payment/Payment.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#10 메인 구독 페이지 UI 추가
  public/images/sampleIcon.png
  sampleIcon.png
  src/Router.jsx
  src/pages/Main/Layout/SUBSCRIPTION.js
  src/pages/Main/Layout/Subscribe.jsx
  src/pages/Main/Layout/Subscribe.scss
  src/pages/Main/Layout/TabContent/TabContent.jsx
  src/pages/Main/Layout/TabContent/TabContent.scss
  src/pages/Main/Layout/TabList/TabList.jsx
  src/pages/Main/Layout/TabList/TabList.scss
  src/pages/Main/Layout/TitleText/TitleText.jsx
  src/pages/Main/Layout/TitleText/TitleText.scss
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청

#18 Nav Bar UI 완성
  src/Router.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/Nav/Cart-icon.png
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#14 결제 완료 페이지 완료
  src/Router.jsx
  src/pages/PayComplete/PayComplete.jsx
  src/pages/PayComplete/PayComplete.scss
Labels: 멘토 리뷰 요청

#21 Nav바 기능구현
  src/Router.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#15 제품 상세페이지 기능 구현
  package-lock.json
  package.json
  public/data/MockData.json
  src/Router.jsx
  src/pages/Detail/Components/Review.jsx
  src/pages/Detail/Components/Review.scss
  src/pages/Detail/Components/Star.jsx
  src/pages/Detail/Components/Star.scss
  src/pages/Detail/Components/StarIcon.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/Detail.scss
  src/pages/Detail/택배.svg
Labels: 멘토 리뷰 요청
